// NOTE: the module-level safety contract in `native.rs` applies to every `extern "C"` function in this file.

use std::ffi::{c_char, c_void};

use crate::occt::Shape;

use super::native_helpers::{shape_result_to_ptr, utf8_arg};

// ---------------------------------------------------------------------------
// Mirror (Phase 2)
// ---------------------------------------------------------------------------

// Spelled out rather than generated by `shape_method!` because its UTF-8 error
// message says "plane name", not the macro's argument-derived "plane".
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rrcad_shape_mirror(
    ptr: *mut c_void,
    plane: *const c_char,
    error_out: *mut *const c_char,
) -> *mut c_void {
    unsafe { *error_out = std::ptr::null() };
    let shape = unsafe { &*(ptr as *const Shape) };
    let Some(plane) = (unsafe { utf8_arg(plane, "plane name", error_out) }) else {
        return std::ptr::null_mut();
    };
    unsafe { shape_result_to_ptr(shape.mirror(plane), error_out) }
}

// ---------------------------------------------------------------------------
// 2D sketch constructors (Phase 2)
// ---------------------------------------------------------------------------

shape_ctor!(rrcad_make_rect(w: f64, h: f64) => Shape::make_rect);
shape_ctor!(rrcad_make_circle_face(r: f64) => Shape::make_circle_face);

#[unsafe(no_mangle)]
pub unsafe extern "C" fn rrcad_make_polygon(
    pts: *const f64,
    n_pts: usize,
    error_out: *mut *const c_char,
) -> *mut c_void {
    unsafe { *error_out = std::ptr::null() };
    let slice = unsafe { std::slice::from_raw_parts(pts, n_pts * 2) };
    unsafe { shape_result_to_ptr(Shape::make_polygon(slice), error_out) }
}

shape_ctor!(rrcad_make_ellipse_face(rx: f64, ry: f64) => Shape::make_ellipse_face);
shape_ctor!(rrcad_make_arc(r: f64, start_deg: f64, end_deg: f64) => Shape::make_arc);

// ---------------------------------------------------------------------------
// Extrude / Revolve (Phase 2)
// ---------------------------------------------------------------------------

shape_method!(rrcad_shape_extrude(height: f64) => extrude);
shape_method!(rrcad_shape_revolve(angle_deg: f64) => revolve);

// ---------------------------------------------------------------------------
// Phase 3: Spline profiles and sweep
//
// The spline / polygon constructors take a caller-owned `f64` slice whose
// length depends on the point stride, so they stay hand-written.
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub unsafe extern "C" fn rrcad_make_spline_2d(
    pts: *const f64,
    n_pts: usize,
    error_out: *mut *const c_char,
) -> *mut c_void {
    unsafe { *error_out = std::ptr::null() };
    let slice = unsafe { std::slice::from_raw_parts(pts, n_pts * 2) };
    unsafe { shape_result_to_ptr(Shape::make_spline_2d(slice), error_out) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn rrcad_make_spline_3d(
    pts: *const f64,
    n_pts: usize,
    error_out: *mut *const c_char,
) -> *mut c_void {
    unsafe { *error_out = std::ptr::null() };
    let slice = unsafe { std::slice::from_raw_parts(pts, n_pts * 3) };
    unsafe { shape_result_to_ptr(Shape::make_spline_3d(slice), error_out) }
}

/// Tangent-constrained 2D spline: explicit start/end tangents in the XZ plane.
/// `tangents` points to a flat array [t0x, t0z, t1x, t1z] (4 doubles).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rrcad_make_spline_2d_tan(
    pts: *const f64,
    n_pts: usize,
    tangents: *const f64,
    error_out: *mut *const c_char,
) -> *mut c_void {
    unsafe { *error_out = std::ptr::null() };
    let slice = unsafe { std::slice::from_raw_parts(pts, n_pts * 2) };
    let t = unsafe { std::slice::from_raw_parts(tangents, 4) };
    unsafe {
        shape_result_to_ptr(
            Shape::make_spline_2d_tan(slice, t[0], t[1], t[2], t[3]),
            error_out,
        )
    }
}

/// Tangent-constrained 3D spline: explicit start/end tangent vectors.
/// `tangents` points to a flat array [t0x, t0y, t0z, t1x, t1y, t1z] (6 doubles).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rrcad_make_spline_3d_tan(
    pts: *const f64,
    n_pts: usize,
    tangents: *const f64,
    error_out: *mut *const c_char,
) -> *mut c_void {
    unsafe { *error_out = std::ptr::null() };
    let slice = unsafe { std::slice::from_raw_parts(pts, n_pts * 3) };
    let t = unsafe { std::slice::from_raw_parts(tangents, 6) };
    unsafe {
        shape_result_to_ptr(
            Shape::make_spline_3d_tan(slice, t[0], t[1], t[2], t[3], t[4], t[5]),
            error_out,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::{
        rrcad_make_arc, rrcad_make_circle_face, rrcad_make_ellipse_face, rrcad_make_polygon,
        rrcad_make_rect, rrcad_make_spline_2d, rrcad_make_spline_2d_tan, rrcad_make_spline_3d,
        rrcad_make_spline_3d_tan, rrcad_shape_extrude, rrcad_shape_mirror, rrcad_shape_revolve,
    };
    use crate::occt::Shape;
    use std::{
        ffi::{CStr, CString},
        os::raw::c_char,
        ptr,
    };

    unsafe fn reclaim_shape(ptr: *mut std::ffi::c_void) {
        if !ptr.is_null() {
            unsafe {
                drop(Box::from_raw(ptr as *mut Shape));
            }
        }
    }

    fn boxed_shape(shape: Shape) -> *mut std::ffi::c_void {
        Box::into_raw(Box::new(shape)) as *mut std::ffi::c_void
    }

    unsafe fn error_message(err: *const c_char) -> Option<String> {
        if err.is_null() {
            None
        } else {
            Some(
                unsafe { CStr::from_ptr(err) }
                    .to_str()
                    .expect("utf8")
                    .to_string(),
            )
        }
    }

    #[test]
    fn constructors_return_shapes() {
        let mut err: *const c_char = ptr::null();
        let rect = unsafe { rrcad_make_rect(10.0, 20.0, &mut err) };
        let circle = unsafe { rrcad_make_circle_face(5.0, &mut err) };
        let ellipse = unsafe { rrcad_make_ellipse_face(6.0, 4.0, &mut err) };
        let arc = unsafe { rrcad_make_arc(5.0, 0.0, 180.0, &mut err) };
        let polygon_points = [0.0, 0.0, 10.0, 0.0, 5.0, 5.0];
        let polygon = unsafe { rrcad_make_polygon(polygon_points.as_ptr(), 3, &mut err) };

        assert!(unsafe { error_message(err) }.is_none());
        assert!(!rect.is_null());
        assert!(!circle.is_null());
        assert!(!ellipse.is_null());
        assert!(!arc.is_null());
        assert!(!polygon.is_null());

        unsafe {
            reclaim_shape(rect);
            reclaim_shape(circle);
            reclaim_shape(ellipse);
            reclaim_shape(arc);
            reclaim_shape(polygon);
        }
    }

    #[test]
    fn extrude_revolve_and_mirror_wrappers_return_shapes() {
        let profile = boxed_shape(Shape::make_rect(10.0, 20.0).unwrap());
        let mut err: *const c_char = ptr::null();

        let extruded = unsafe { rrcad_shape_extrude(profile, 5.0, &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!extruded.is_null());

        let revolved = unsafe { rrcad_shape_revolve(profile, 180.0, &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!revolved.is_null());

        let mirror =
            unsafe { rrcad_shape_mirror(profile, CString::new("xy").unwrap().as_ptr(), &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!mirror.is_null());

        unsafe {
            reclaim_shape(profile);
            reclaim_shape(extruded);
            reclaim_shape(revolved);
            reclaim_shape(mirror);
        }
    }

    #[test]
    fn spline_wrappers_return_shapes() {
        let pts2d = [0.0, 0.0, 5.0, 5.0, 10.0, 0.0];
        let pts3d = [0.0, 0.0, 0.0, 5.0, 0.0, 2.0, 10.0, 0.0, 0.0];
        let tan2d = [1.0, 0.0, -1.0, 0.0];
        let tan3d = [1.0, 0.0, 0.0, -1.0, 0.0, 0.0];
        let mut err: *const c_char = ptr::null();

        let spline2d = unsafe { rrcad_make_spline_2d(pts2d.as_ptr(), 3, &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!spline2d.is_null());

        let spline3d = unsafe { rrcad_make_spline_3d(pts3d.as_ptr(), 3, &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!spline3d.is_null());

        let spline2d_tan =
            unsafe { rrcad_make_spline_2d_tan(pts2d.as_ptr(), 3, tan2d.as_ptr(), &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!spline2d_tan.is_null());

        let spline3d_tan =
            unsafe { rrcad_make_spline_3d_tan(pts3d.as_ptr(), 3, tan3d.as_ptr(), &mut err) };
        assert!(unsafe { error_message(err) }.is_none());
        assert!(!spline3d_tan.is_null());

        unsafe {
            reclaim_shape(spline2d);
            reclaim_shape(spline3d);
            reclaim_shape(spline2d_tan);
            reclaim_shape(spline3d_tan);
        }
    }
}
